#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include <doctest/doctest.h>

#include "companion_protocol/live_signal_layout.hpp"
#include "companion_protocol/live_signals.hpp"

// Test harness only: the private seam binds the facade's production service to
// an injected clock, host acquisition source and lighting sink, so generated
// frames reach the production Mazda provider and its default freshness policy.
#include "mazda/definitions.hpp"
#include "mazda/signal_provider.hpp"
#include "mazda/vehicle_telemetry.hpp"
#include "mazda/vehicle_telemetry_internal.hpp"

#include <atomic>
#include <chrono>
#include <cstddef>
#include <cstdint>
#include <initializer_list>
#include <thread>

namespace {

namespace candidate = mazda::candidate;
using companion_protocol::kLiveSignalCount;
using companion_protocol::live_signal_slots;
using companion_protocol::LiveFrame;
using companion_protocol::LiveSignalSampler;
using vehicle_signals::SignalType;

class FakeClock final : public vehicle_core::MonotonicClock {
public:
  [[nodiscard]] vehicle_core::MonotonicTimestamp now() const noexcept override {
    return now_us_.load(std::memory_order_relaxed);
  }
  void set(const vehicle_core::MonotonicTimestamp value) noexcept {
    now_us_.store(value, std::memory_order_relaxed);
  }

private:
  std::atomic<vehicle_core::MonotonicTimestamp> now_us_{0};
};

vehicle_core::RawCanFrame frame(const std::uint32_t identifier,
                                const vehicle_core::MonotonicTimestamp timestamp_us,
                                std::initializer_list<std::uint8_t> bytes) {
  vehicle_core::RawCanFrame result{};
  result.identifier = identifier;
  result.timestamp_us = timestamp_us;
  result.dlc = static_cast<std::uint8_t>(bytes.size());
  std::size_t index = 0;
  for (const auto byte : bytes) {
    result.data[index++] = byte;
  }
  return result;
}

// Generated byte patterns, not captures. BRAKE_PEDAL D1 bit 4 is pressed;
// ENGINE_DATA 0x095b is 598.75 rpm.
constexpr std::initializer_list<std::uint8_t> kBrakePressed{0x10, 0, 0, 0, 0, 0, 0, 0};
constexpr std::initializer_list<std::uint8_t> kEngine59875{0x09, 0x5b, 0, 0, 0, 0, 0, 0};

template <typename Predicate>
bool wait_for(Predicate predicate,
              const std::chrono::milliseconds timeout = std::chrono::milliseconds{1000}) {
  const auto deadline = std::chrono::steady_clock::now() + timeout;
  while (std::chrono::steady_clock::now() < deadline) {
    if (predicate()) {
      return true;
    }
    std::this_thread::sleep_for(std::chrono::milliseconds{1});
  }
  return predicate();
}

struct Harness final {
  Harness() noexcept {
    mazda::TelemetryConfig config{};
    config.callback_stop_timeout_us = 20'000;
    mazda::internal::VehicleTelemetryAccess::emplace_host_service(telemetry, clock, source,
                                                                  lighting, config);
  }
  ~Harness() {
    if (telemetry.diagnostics().lifecycle != mazda::LifecycleState::Stopped) {
      (void)telemetry.stop();
    }
  }
  Harness(const Harness &) = delete;
  Harness &operator=(const Harness &) = delete;

  void inject(const std::uint32_t identifier, const vehicle_core::MonotonicTimestamp timestamp_us,
              std::initializer_list<std::uint8_t> bytes) {
    clock.set(timestamp_us);
    CHECK(source.inject(frame(identifier, timestamp_us, bytes)) == mazda::ResultCode::Ok);
  }

  FakeClock clock{};
  mazda::internal::HostAcquisitionSource source{};
  mazda::internal::NullLightingSink lighting{};
  mazda::VehicleTelemetry telemetry{};
  mazda::MazdaSignalProvider provider{telemetry};
};

std::uint8_t nibble(const LiveFrame &frame, std::size_t slot) {
  const std::uint8_t byte = frame[13 + slot / 2];
  return static_cast<std::uint8_t>(slot % 2 == 0 ? byte & 0x0FU : byte >> 4U);
}

constexpr std::size_t kRpmSlot = 0;
constexpr std::size_t kBrakeSlot = 18;
constexpr std::uint8_t kValuePresent = 0x08;
constexpr std::uint8_t kFreshnessUnverified = 3;
constexpr std::uint8_t kUnavailable = 4;

} // namespace

TEST_CASE("every live signal key resolves in the production catalog with its type") {
  Harness harness;
  const auto catalog = harness.provider.catalog();
  for (const auto &slot : live_signal_slots()) {
    const auto *entry = catalog.find(slot.key);
    REQUIRE_MESSAGE(entry != nullptr, slot.key);
    CHECK(entry->type == slot.type);
    CHECK(entry->capabilities.has(vehicle_signals::SignalCapability::Read));
  }
}

TEST_CASE("every production catalog choice of an Enum slot has a protocol code") {
  Harness harness;
  const auto catalog = harness.provider.catalog();
  for (const auto &slot : live_signal_slots()) {
    if (slot.type != SignalType::Enum) {
      continue;
    }
    const auto *entry = catalog.find(slot.key);
    REQUIRE(entry != nullptr);
    for (std::size_t index = 0; index < entry->choice_count; ++index) {
      CHECK_MESSAGE(slot.choice_code(entry->choices[index].key).has_value(),
                    entry->choices[index].key);
    }
  }
}

TEST_CASE("before the facade starts the provider's Unavailable is copied with no value") {
  Harness harness;
  const LiveSignalSampler sampler{harness.provider};
  const auto frame = sampler.sample(false).frame(0);
  CHECK(frame[2] == 0x00);
  for (std::size_t slot = 0; slot < kLiveSignalCount; ++slot) {
    CHECK(nibble(frame, slot) == kUnavailable);
  }
}

TEST_CASE("production brake and rpm readings never encode as Fresh") {
  Harness harness;
  REQUIRE(harness.telemetry.start().ok());
  const LiveSignalSampler sampler{harness.provider};
  harness.inject(candidate::kBrakePedalId, 1'000, kBrakePressed);
  harness.inject(candidate::kEngineDataId, 1'000, kEngine59875);

  const auto both_present = [&] {
    const auto frame = sampler.sample(true).frame(0);
    return (nibble(frame, kRpmSlot) & kValuePresent) != 0 &&
           (nibble(frame, kBrakeSlot) & kValuePresent) != 0;
  };
  REQUIRE(wait_for(both_present));

  const auto frame = sampler.sample(true).frame(0);
  CHECK(nibble(frame, kBrakeSlot) == (kValuePresent | kFreshnessUnverified));
  CHECK(nibble(frame, kRpmSlot) == (kValuePresent | kFreshnessUnverified));
  CHECK((frame[11] | (frame[12] << 8U)) == (1U << 12U));
  CHECK((frame[3] | (frame[4] << 8U)) == 2395);
  CHECK(frame[2] == 0x01);
}
