#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include <doctest/doctest.h>

#include "generic_signal_consumer.hpp"

// Test harness only: the private seam binds the facade's production service to
// an injected clock, host acquisition source and lighting sink. The consumer
// above is compiled separately without these include paths.
#include "mazda/definitions.hpp"
#include "mazda/vehicle_telemetry.hpp"
#include "mazda/vehicle_telemetry_internal.hpp"

#include <array>
#include <atomic>
#include <chrono>
#include <condition_variable>
#include <cstddef>
#include <cstdint>
#include <initializer_list>
#include <mutex>
#include <optional>
#include <string_view>
#include <thread>
#include <type_traits>

namespace {

namespace candidate = mazda::candidate;
using generic_signal_consumer::choice_key;
using generic_signal_consumer::GenericSignalConsumer;
using mazda::Availability;
using mazda::SelectorPosition;
using mazda::TurnState;
using vehicle_signals::SignalCapability;
using vehicle_signals::SignalMetadata;
using vehicle_signals::SignalNotification;
using vehicle_signals::SignalReading;
using vehicle_signals::SignalStatus;
using vehicle_signals::SignalSubscription;
using vehicle_signals::SignalValue;

// The service reads the clock from its own thread, so the fake is atomic.
class FakeClock final : public vehicle_core::MonotonicClock {
public:
  [[nodiscard]] vehicle_core::MonotonicTimestamp now() const noexcept override {
    return now_us_.load(std::memory_order_relaxed);
  }
  void set(const vehicle_core::MonotonicTimestamp value) noexcept {
    now_us_.store(value, std::memory_order_relaxed);
  }

private:
  std::atomic<vehicle_core::MonotonicTimestamp> now_us_{0};
};

vehicle_core::RawCanFrame frame(const std::uint32_t identifier,
                                const vehicle_core::MonotonicTimestamp timestamp_us,
                                std::initializer_list<std::uint8_t> bytes) {
  vehicle_core::RawCanFrame result{};
  result.identifier = identifier;
  result.timestamp_us = timestamp_us;
  result.dlc = static_cast<std::uint8_t>(bytes.size());
  std::size_t index = 0;
  for (const auto byte : bytes) {
    result.data[index++] = byte;
  }
  return result;
}

// Generated byte patterns shared with the decoder fixtures and the provider
// read/subscription tests; none is a capture.
// ENGINE_DATA: 0x095b is 598.75 rpm; 0x0001 is 0.25 rpm; speed bytes are zero.
constexpr std::initializer_list<std::uint8_t> kEngine59875{0x09, 0x5b, 0, 0, 0, 0, 0, 0};
constexpr std::initializer_list<std::uint8_t> kEngine025{0x00, 0x01, 0, 0, 0, 0, 0, 0};
// TRANSMISSION: selector Drive, actual gear Second.
constexpr std::initializer_list<std::uint8_t> kGearDrive{0x24, 0x81, 0x07, 0xff, 0x04, 0xf0, 0, 0};
// TURN_SWITCH: D2 bit 5 left, bit 4 right, bit 2 hazard; D3 bits 4-5 front
// wiper (1 = On).
constexpr std::initializer_list<std::uint8_t> kTurnLeft{0, 0x20, 0x10, 0, 0, 0, 0, 0};
constexpr std::initializer_list<std::uint8_t> kTurnRight{0, 0x10, 0, 0, 0, 0, 0, 0};
constexpr std::initializer_list<std::uint8_t> kTurnHazard{0, 0x04, 0, 0, 0, 0, 0, 0};
constexpr std::initializer_list<std::uint8_t> kTurnNone{0, 0, 0, 0, 0, 0, 0, 0};
// BLINK_INFO: D3 bit 2 left lamp, bit 3 right lamp; D5 bit 1 WiperLow.
constexpr std::initializer_list<std::uint8_t> kBlinkRightLampWiperLow{0, 0, 0x08, 0, 0x02, 0, 0, 0};
constexpr std::initializer_list<std::uint8_t> kBlinkLeftLamp{0, 0, 0x04, 0, 0, 0, 0, 0};
// DOORS: D4 bit 6 unlocked; D5 bits 0, 2, 3, 4, 5 liftgate and doors open.
constexpr std::initializer_list<std::uint8_t> kDoorsAllOpen{0, 0, 0, 0x40, 0x3d, 0, 0, 0};

template <typename Predicate>
bool wait_for(Predicate predicate,
              const std::chrono::milliseconds timeout = std::chrono::milliseconds{1000}) {
  const auto deadline = std::chrono::steady_clock::now() + timeout;
  while (std::chrono::steady_clock::now() < deadline) {
    if (predicate()) {
      return true;
    }
    std::this_thread::sleep_for(std::chrono::milliseconds{1});
  }
  return predicate();
}

// The facade runs the production runtime, Mazda decoder and publication path
// over the injected seams. The destructor stops the facade before the
// consumer (its callback context) and the provider are destroyed.
struct Harness final {
  explicit Harness(const mazda::TelemetryConfig &config = test_config()) noexcept {
    mazda::internal::VehicleTelemetryAccess::emplace_host_service(telemetry, clock, source,
                                                                  lighting, config);
  }
  ~Harness() {
    if (telemetry.diagnostics().lifecycle != mazda::LifecycleState::Stopped) {
      (void)telemetry.stop();
    }
  }

  Harness(const Harness &) = delete;
  Harness &operator=(const Harness &) = delete;

  static mazda::TelemetryConfig test_config() noexcept {
    mazda::TelemetryConfig config{};
    config.callback_stop_timeout_us = 20'000;
    return config;
  }

  // Holding the clock at the frame time makes generic and typed evaluations of
  // one publication happen at the same instant.
  void inject(const std::uint32_t identifier, const vehicle_core::MonotonicTimestamp timestamp_us,
              std::initializer_list<std::uint8_t> bytes) {
    clock.set(timestamp_us);
    CHECK(source.inject(frame(identifier, timestamp_us, bytes)) == mazda::ResultCode::Ok);
  }

  FakeClock clock{};
  mazda::internal::HostAcquisitionSource source{};
  mazda::internal::NullLightingSink lighting{};
  mazda::VehicleTelemetry telemetry{};
  mazda::MazdaSignalProvider provider{telemetry};
  GenericSignalConsumer consumer{provider};
};

// ---------------------------------------------------------------------------
// Independent typed/generic comparison. It does not use the provider's
// converter: Mazda enums compare by their raw enumerator value.

bool same_value(const SignalValue &generic, const bool typed) {
  return generic.as_boolean() == std::optional<bool>{typed};
}
bool same_value(const SignalValue &generic, const float typed) {
  return generic.as_number() == std::optional<float>{typed};
}
template <typename Enum, std::enable_if_t<std::is_enum_v<Enum>, int> = 0>
bool same_value(const SignalValue &generic, const Enum typed) {
  return generic.as_enumeration() ==
         std::optional<std::uint16_t>{static_cast<std::uint16_t>(typed)};
}

template <typename T>
bool same_reading(const SignalReading &generic, const mazda::Reading<T> &typed) {
  if (generic.value.has_value() != typed.value.has_value()) {
    return false;
  }
  if (typed.value.has_value() && !same_value(*generic.value, *typed.value)) {
    return false;
  }
  return generic.availability == typed.availability && generic.validation == typed.validation;
}

template <typename T>
bool same_notice(const SignalNotification &generic, const mazda::Notification<T> &typed) {
  return same_reading(generic.current, typed.current) && generic.initial == typed.initial &&
         generic.became_unavailable == typed.became_unavailable &&
         generic.recovered == typed.recovered && generic.coalesced == typed.coalesced;
}

bool same_generic_reading(const SignalReading &left, const SignalReading &right) {
  return left.value == right.value && left.availability == right.availability &&
         left.validation == right.validation;
}

// Typed recorder with an optional gate that holds the shared dispatcher inside
// the callback on a chosen value.
template <typename T> struct TypedRecorder final {
  mutable std::mutex mutex{};
  std::condition_variable changed{};
  mazda::Notification<T> latest{};
  std::size_t count{0};
  std::optional<T> block_on{};
  bool blocked{false};
  bool released{false};

  [[nodiscard]] std::optional<mazda::Notification<T>> snapshot() const {
    std::lock_guard<std::mutex> lock{mutex};
    if (count == 0) {
      return std::nullopt;
    }
    return latest;
  }
  [[nodiscard]] bool wait_until_blocked() {
    std::unique_lock<std::mutex> lock{mutex};
    return changed.wait_for(lock, std::chrono::milliseconds{1000}, [this] { return blocked; });
  }
  void release() {
    {
      std::lock_guard<std::mutex> lock{mutex};
      released = true;
    }
    changed.notify_all();
  }
};

template <typename T>
void record_typed(void *context, const mazda::Notification<T> &notice) noexcept {
  auto &recorder = *static_cast<TypedRecorder<T> *>(context);
  std::unique_lock<std::mutex> lock{recorder.mutex};
  recorder.latest = notice;
  ++recorder.count;
  if (recorder.block_on.has_value() && notice.current.value == recorder.block_on) {
    recorder.blocked = true;
    recorder.changed.notify_all();
    recorder.changed.wait(lock, [&recorder] { return recorder.released; });
  }
}

struct GenericRecorder final {
  mutable std::mutex mutex{};
  SignalNotification latest{};
  std::size_t count{0};

  [[nodiscard]] std::optional<SignalNotification> snapshot() const {
    std::lock_guard<std::mutex> lock{mutex};
    if (count == 0) {
      return std::nullopt;
    }
    return latest;
  }
};

void record_generic(void *context, const SignalNotification &notice) noexcept {
  auto &recorder = *static_cast<GenericRecorder *>(context);
  std::lock_guard<std::mutex> lock{recorder.mutex};
  recorder.latest = notice;
  ++recorder.count;
}

template <typename T>
bool notices_match(const std::optional<SignalNotification> &generic,
                   const std::optional<mazda::Notification<T>> &typed) {
  return generic.has_value() && typed.has_value() && same_notice(*generic, *typed);
}

template <typename T>
bool both_hold(const std::optional<SignalNotification> &generic,
               const std::optional<mazda::Notification<T>> &typed, const T expected) {
  return generic.has_value() && typed.has_value() && typed->current.value == expected &&
         generic->current.value.has_value() && same_value(*generic->current.value, expected);
}

const SignalMetadata &signal(const Harness &harness, const std::string_view key) {
  const SignalMetadata *entry = harness.provider.catalog().find(key);
  REQUIRE(entry != nullptr);
  return *entry;
}

} // namespace

TEST_CASE("generic consumer resolves canonical keys and matches typed RPM reads") {
  Harness harness{};
  auto &consumer = harness.consumer;
  // Nothing resolved yet: a request failure, not a NoData reading.
  CHECK(consumer.read_engine_rpm().status == SignalStatus::InvalidSignal);
  REQUIRE(consumer.attach() == SignalStatus::Ok);
  REQUIRE(consumer.engine_rpm_signal() != nullptr);
  CHECK(consumer.engine_rpm_signal()->key == generic_signal_consumer::kEngineRpmKey);
  CHECK(consumer.engine_rpm_signal()->unit == vehicle_signals::SignalUnit::RevolutionsPerMinute);
  CHECK(consumer.engine_rpm_signal()->capabilities == SignalCapability::Read);
  CHECK(harness.provider.catalog().find(consumer.engine_rpm_signal()->id) ==
        consumer.engine_rpm_signal());

  REQUIRE(harness.telemetry.start().ok());
  const auto before = consumer.read_engine_rpm();
  REQUIRE(before.ok());
  CHECK(before.value->availability == Availability::NoData);
  CHECK(same_reading(*before.value, harness.telemetry.engine_rpm()));

  harness.inject(candidate::kEngineDataId, 500, kEngine59875);
  CHECK(wait_for([&consumer] {
    const auto rpm = consumer.read_engine_rpm();
    return rpm.ok() && rpm.value->value.has_value();
  }));
  const auto rpm = consumer.read_engine_rpm();
  REQUIRE(rpm.ok());
  CHECK(rpm.value->value == std::optional<SignalValue>{SignalValue::number(598.75F)});
  CHECK(same_reading(*rpm.value, harness.telemetry.engine_rpm()));

  // A transport fault makes both paths Unavailable while keeping the value.
  harness.source.fail();
  CHECK(wait_for([&harness] {
    const auto faulted = harness.consumer.read_engine_rpm();
    return faulted.ok() && faulted.value->availability == Availability::Unavailable;
  }));
  const auto faulted = consumer.read_engine_rpm();
  REQUIRE(faulted.ok());
  CHECK(faulted.value->value.has_value());
  CHECK(same_reading(*faulted.value, harness.telemetry.engine_rpm()));

  CHECK(harness.telemetry.stop().status == mazda::ResultCode::Faulted);
  CHECK(consumer.detach() == SignalStatus::Ok);
}

TEST_CASE("generic turn notices match typed notices including all flags") {
  // Short transport silence gives one direct usable -> Unavailable transition
  // before the 250 ms turn freshness timeout could publish Stale.
  auto config = Harness::test_config();
  config.transport_silence_timeout_us = 100;
  Harness harness{config};
  auto &consumer = harness.consumer;
  TypedRecorder<TurnState> typed{};
  typed.block_on = TurnState::Left;
  const auto turn_notices_match = [&] {
    return notices_match(consumer.latest_turn_notice(), typed.snapshot());
  };
  const auto current_read_matches = [&] {
    const auto read = harness.provider.read(consumer.turn_state_signal()->id);
    const auto notice = consumer.latest_turn_notice();
    return read.ok() && notice.has_value() && same_generic_reading(*read.value, notice->current);
  };

  // Subscriptions are stopped-only mutations on the lifecycle owner (this
  // thread). Generic and typed subscribers fill the channel's two slots.
  REQUIRE(consumer.attach() == SignalStatus::Ok);
  const auto typed_subscription =
      harness.telemetry.on_turn_state_changed(&record_typed<TurnState>, &typed);
  REQUIRE(typed_subscription.ok());
  REQUIRE(harness.telemetry.start().ok());

  // initial
  CHECK(wait_for([&] { return consumer.turn_notice_count() >= 1 && typed.snapshot(); }));
  auto generic = consumer.latest_turn_notice();
  REQUIRE(generic.has_value());
  CHECK(generic->id == consumer.turn_state_signal()->id);
  CHECK(generic->initial);
  CHECK(generic->current.availability == Availability::NoData);
  CHECK(turn_notices_match());

  // coalesced: hold the shared dispatcher in the typed callback on Left while
  // Right and Hazard are published. Two later RPM publications prove the
  // processing owner finished the pass that published Hazard.
  harness.inject(candidate::kTurnSwitchId, 10, kTurnLeft);
  REQUIRE(typed.wait_until_blocked());
  harness.inject(candidate::kTurnSwitchId, 11, kTurnRight);
  harness.inject(candidate::kTurnSwitchId, 12, kTurnHazard);
  harness.inject(candidate::kEngineDataId, 13, kEngine59875);
  CHECK(wait_for([&harness] { return harness.telemetry.engine_rpm().value == 598.75F; }));
  harness.inject(candidate::kEngineDataId, 14, kEngine025);
  CHECK(wait_for([&harness] { return harness.telemetry.engine_rpm().value == 0.25F; }));
  typed.release();
  CHECK(wait_for([&] {
    return both_hold(consumer.latest_turn_notice(), typed.snapshot(), TurnState::Hazard);
  }));
  generic = consumer.latest_turn_notice();
  REQUIRE(generic.has_value());
  CHECK(generic->coalesced);
  CHECK(!generic->initial);
  CHECK(generic->current.availability == Availability::Fresh);
  CHECK(consumer.turn_choice(generic->current) == "hazard");
  CHECK(turn_notices_match());
  CHECK(current_read_matches());

  // became_unavailable: transport silence at the held clock; RPM follows on
  // both paths too.
  harness.clock.set(200);
  CHECK(wait_for([&] {
    const auto notice = consumer.latest_turn_notice();
    const auto typed_notice = typed.snapshot();
    return notice.has_value() && notice->became_unavailable && typed_notice.has_value() &&
           typed_notice->became_unavailable;
  }));
  generic = consumer.latest_turn_notice();
  REQUIRE(generic.has_value());
  CHECK(generic->current.availability == Availability::Unavailable);
  CHECK(turn_notices_match());
  CHECK(current_read_matches());
  CHECK(same_reading(*consumer.read_engine_rpm().value, harness.telemetry.engine_rpm()));

  // recovered: a fresh frame after an earlier usable period in this run.
  harness.inject(candidate::kTurnSwitchId, 201, kTurnRight);
  CHECK(wait_for([&] {
    const auto notice = consumer.latest_turn_notice();
    const auto typed_notice = typed.snapshot();
    return notice.has_value() && notice->recovered && typed_notice.has_value() &&
           typed_notice->recovered;
  }));
  generic = consumer.latest_turn_notice();
  REQUIRE(generic.has_value());
  CHECK(consumer.turn_choice(generic->current) == "right");
  CHECK(!generic->became_unavailable);
  CHECK(turn_notices_match());
  CHECK(current_read_matches());

  REQUIRE(harness.telemetry.stop().ok());
  CHECK(consumer.detach() == SignalStatus::Ok);
  CHECK(harness.telemetry.unsubscribe(*typed_subscription.value).ok());
}

TEST_CASE("turn request and lamp stay distinct with enum and malformed-frame parity") {
  Harness harness{};
  auto &provider = harness.provider;
  const auto &request = signal(harness, "vehicle.turn_request.left");
  const auto &lamp = signal(harness, "vehicle.indicator_lamp.left");
  const auto &selector = signal(harness, "vehicle.selector_position");
  GenericRecorder generic_request{};
  GenericRecorder generic_lamp{};
  GenericRecorder generic_selector{};
  TypedRecorder<bool> typed_request{};
  TypedRecorder<bool> typed_lamp{};
  TypedRecorder<SelectorPosition> typed_selector{};

  const auto request_subscription =
      provider.subscribe(request.id, &record_generic, &generic_request);
  const auto lamp_subscription = provider.subscribe(lamp.id, &record_generic, &generic_lamp);
  const auto selector_subscription =
      provider.subscribe(selector.id, &record_generic, &generic_selector);
  REQUIRE(request_subscription.ok());
  REQUIRE(lamp_subscription.ok());
  REQUIRE(selector_subscription.ok());
  const auto typed_request_subscription =
      harness.telemetry.on_left_turn_request_changed(&record_typed<bool>, &typed_request);
  const auto typed_lamp_subscription =
      harness.telemetry.on_left_indicator_lamp_changed(&record_typed<bool>, &typed_lamp);
  const auto typed_selector_subscription = harness.telemetry.on_selector_position_changed(
      &record_typed<SelectorPosition>, &typed_selector);
  REQUIRE(typed_request_subscription.ok());
  REQUIRE(typed_lamp_subscription.ok());
  REQUIRE(typed_selector_subscription.ok());

  const auto all_match = [&] {
    return notices_match(generic_request.snapshot(), typed_request.snapshot()) &&
           notices_match(generic_lamp.snapshot(), typed_lamp.snapshot()) &&
           notices_match(generic_selector.snapshot(), typed_selector.snapshot());
  };
  REQUIRE(harness.telemetry.start().ok());
  CHECK(wait_for(all_match));
  CHECK(generic_request.snapshot()->initial);

  // TURN_SWITCH sets the left request; BLINK_INFO lights only the right lamp,
  // so the left request and the left lamp disagree. TRANSMISSION is Drive.
  harness.inject(candidate::kTurnSwitchId, 1'000, kTurnLeft);
  harness.inject(candidate::kBlinkInfoId, 1'000, kBlinkRightLampWiperLow);
  harness.inject(candidate::kGearId, 1'000, kGearDrive);
  CHECK(wait_for([&] {
    return both_hold(generic_request.snapshot(), typed_request.snapshot(), true) &&
           both_hold(generic_lamp.snapshot(), typed_lamp.snapshot(), false) &&
           both_hold(generic_selector.snapshot(), typed_selector.snapshot(),
                     SelectorPosition::Drive);
  }));
  CHECK(all_match());
  CHECK(choice_key(selector, generic_selector.snapshot()->current) == "drive");
  CHECK(selector.accepts(*generic_selector.snapshot()->current.value));

  // A short BLINK_INFO frame faults that message only: the lamp becomes
  // unavailable on both paths while the request from TURN_SWITCH is unchanged.
  harness.inject(candidate::kBlinkInfoId, 1'001, {0});
  CHECK(wait_for([&] {
    const auto generic = generic_lamp.snapshot();
    const auto typed = typed_lamp.snapshot();
    return generic.has_value() && generic->became_unavailable && typed.has_value() &&
           typed->became_unavailable;
  }));
  CHECK(generic_lamp.snapshot()->current.availability == Availability::Unavailable);
  CHECK(all_match());
  const auto request_read = provider.read(request.id);
  REQUIRE(request_read.ok());
  CHECK(request_read.value->value == std::optional<SignalValue>{SignalValue::boolean(true)});
  CHECK(request_read.value->availability == Availability::Fresh);

  // The left lamp recovers from its own frame; the request stays set. Then
  // the request clears from its own frame while the lamp stays lit.
  harness.inject(candidate::kBlinkInfoId, 1'002, kBlinkLeftLamp);
  CHECK(wait_for([&] {
    return both_hold(generic_lamp.snapshot(), typed_lamp.snapshot(), true) &&
           generic_lamp.snapshot()->recovered;
  }));
  CHECK(all_match());
  CHECK(provider.read(request.id).value->value ==
        std::optional<SignalValue>{SignalValue::boolean(true)});
  harness.inject(candidate::kTurnSwitchId, 1'003, kTurnNone);
  CHECK(wait_for(
      [&] { return both_hold(generic_request.snapshot(), typed_request.snapshot(), false); }));
  CHECK(all_match());
  CHECK(provider.read(lamp.id).value->value ==
        std::optional<SignalValue>{SignalValue::boolean(true)});

  REQUIRE(harness.telemetry.stop().ok());
  CHECK(provider.unsubscribe(*request_subscription.value).ok());
  CHECK(provider.unsubscribe(*lamp_subscription.value).ok());
  CHECK(provider.unsubscribe(*selector_subscription.value).ok());
  CHECK(harness.telemetry.unsubscribe(*typed_request_subscription.value).ok());
  CHECK(harness.telemetry.unsubscribe(*typed_lamp_subscription.value).ok());
  CHECK(harness.telemetry.unsubscribe(*typed_selector_subscription.value).ok());
}

TEST_CASE("every catalog row works end to end through the public provider") {
  constexpr std::size_t kRows = 18;
  Harness harness{};
  auto &provider = harness.provider;
  const auto catalog = provider.catalog();
  REQUIRE(catalog.size() == kRows);
  CHECK(catalog.well_formed());

  std::array<GenericRecorder, kRows> recorders{};
  std::array<SignalSubscription, kRows> subscriptions{};
  std::size_t notify_rows = 0;
  for (std::size_t index = 0; index < kRows; ++index) {
    const SignalMetadata &row = *catalog.at(index);
    INFO(row.key);
    CHECK(row.capabilities.has(SignalCapability::Read));
    const auto subscription = provider.subscribe(row.id, &record_generic, &recorders[index]);
    if (row.capabilities.has(SignalCapability::Notify)) {
      ++notify_rows;
      REQUIRE(subscription.ok());
      subscriptions[index] = *subscription.value;
    } else {
      CHECK(subscription.status == SignalStatus::UnsupportedCapability);
      CHECK((row.key == "vehicle.engine_rpm" || row.key == "vehicle.speed_kph"));
    }
  }
  CHECK(notify_rows == 16);

  REQUIRE(harness.telemetry.start().ok());
  for (const auto &row : catalog) {
    INFO(row.key);
    const auto result = provider.read(row.id);
    REQUIRE(result.ok());
    CHECK(!result.value->value.has_value());
    CHECK(result.value->availability == Availability::NoData);
    CHECK(result.value->validation == row.validation);
  }

  harness.inject(candidate::kEngineDataId, 1'000, kEngine59875);
  harness.inject(candidate::kGearId, 1'000, kGearDrive);
  harness.inject(candidate::kTurnSwitchId, 1'000, kTurnLeft);
  harness.inject(candidate::kBlinkInfoId, 1'000, kBlinkRightLampWiperLow);
  harness.inject(candidate::kDoorsId, 1'000, kDoorsAllOpen);

  // Each row reads a typed value its metadata accepts, and each Notify row's
  // latest notice carries exactly that reading.
  for (std::size_t index = 0; index < kRows; ++index) {
    const SignalMetadata &row = *catalog.at(index);
    INFO(row.key);
    CHECK(wait_for([&] {
      const auto result = provider.read(row.id);
      if (!result.ok() || !result.value->value.has_value()) {
        return false;
      }
      if (!row.capabilities.has(SignalCapability::Notify)) {
        return true;
      }
      const auto notice = recorders[index].snapshot();
      return notice.has_value() && notice->id == row.id &&
             same_generic_reading(notice->current, *result.value);
    }));
    const auto result = provider.read(row.id);
    REQUIRE(result.ok());
    REQUIRE(result.value->value.has_value());
    CHECK(result.value->value->type() == row.type);
    CHECK(row.accepts(*result.value->value));
    CHECK(result.value->validation == row.validation);
    if (row.type == vehicle_signals::SignalType::Enum) {
      CHECK(!choice_key(row, *result.value).empty());
    }
  }

  REQUIRE(harness.telemetry.stop().ok());
  for (std::size_t index = 0; index < kRows; ++index) {
    if (subscriptions[index].valid()) {
      CHECK(provider.unsubscribe(subscriptions[index]).ok());
    }
  }
}
